{"time":"2025-05-31T13:34:24.8987224+08:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2025-05-31T13:34:24.8987224+08:00","level":"INFO","msg":"created symlink","path":"E:\\Desktop\\Documents\\Git\\minimind\\trainer\\wandb\\run-20250531_133424-w0dl1gct\\logs\\debug-core.log"}
{"time":"2025-05-31T13:34:24.8997452+08:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2025-05-31T13:34:24.9241512+08:00","level":"INFO","msg":"created new stream","id":"w0dl1gct"}
{"time":"2025-05-31T13:34:24.9256927+08:00","level":"INFO","msg":"stream: started","id":"w0dl1gct"}
{"time":"2025-05-31T13:34:24.9256927+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"w0dl1gct"}}
{"time":"2025-05-31T13:34:24.9256927+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"w0dl1gct"}}
{"time":"2025-05-31T13:34:24.9256927+08:00","level":"INFO","msg":"sender: started","stream_id":{"value":"w0dl1gct"}}
{"time":"2025-05-31T13:34:46.0326942+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-31T13:35:09.5620188+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-31T13:35:15.345319+08:00","level":"INFO","msg":"stream: closing","id":"w0dl1gct"}
