{"time":"2025-06-03T13:45:30.0978891+08:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2025-06-03T13:45:30.0978891+08:00","level":"INFO","msg":"created symlink","path":"E:\\Desktop\\Documents\\Git\\minimind\\trainer\\wandb\\run-20250603_134530-eoy0xfva\\logs\\debug-core.log"}
{"time":"2025-06-03T13:45:30.0989662+08:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2025-06-03T13:45:30.6922615+08:00","level":"INFO","msg":"created new stream","id":"eoy0xfva"}
{"time":"2025-06-03T13:45:30.6938652+08:00","level":"INFO","msg":"stream: started","id":"eoy0xfva"}
{"time":"2025-06-03T13:45:30.6938652+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:45:30.6938652+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:45:30.6938652+08:00","level":"INFO","msg":"sender: started","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:45:51.7514984+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T13:46:15.2536923+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T13:46:41.0564626+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T13:47:02.484334+08:00","level":"INFO","msg":"stream: closing","id":"eoy0xfva"}
{"time":"2025-06-03T13:47:02.484334+08:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 4 attempt(s): context canceled"}
{"time":"2025-06-03T13:47:02.484334+08:00","level":"INFO","msg":"handler: closed","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:47:02.484334+08:00","level":"INFO","msg":"writer: Close: closed","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:47:02.484334+08:00","level":"ERROR","msg":"runwork: ignoring record after close","work":{"Record":{"RecordType":{"Request":{"RequestType":{"Defer":{}}}},"control":{"always_send":true}}}}
{"time":"2025-06-03T13:47:02.4861036+08:00","level":"INFO","msg":"sender: closed","stream_id":{"value":"eoy0xfva"}}
{"time":"2025-06-03T13:47:02.4861036+08:00","level":"INFO","msg":"stream: closed","id":"eoy0xfva"}
