{"time":"2025-05-30T19:07:51.7061647+08:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2025-05-30T19:07:51.7061647+08:00","level":"INFO","msg":"created symlink","path":"E:\\Desktop\\Documents\\Git\\minimind\\trainer\\wandb\\run-20250530_190751-5xkyptt8\\logs\\debug-core.log"}
{"time":"2025-05-30T19:07:51.706677+08:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2025-05-30T19:07:51.7326662+08:00","level":"INFO","msg":"created new stream","id":"5xkyptt8"}
{"time":"2025-05-30T19:07:51.7331688+08:00","level":"INFO","msg":"stream: started","id":"5xkyptt8"}
{"time":"2025-05-30T19:07:51.7331688+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"5xkyptt8"}}
{"time":"2025-05-30T19:07:51.7331688+08:00","level":"INFO","msg":"sender: started","stream_id":{"value":"5xkyptt8"}}
{"time":"2025-05-30T19:07:51.7331688+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"5xkyptt8"}}
{"time":"2025-05-30T19:07:52.629641+08:00","level":"INFO","msg":"wandb-core","!BADKEY":null}
{"time":"2025-05-30T19:07:52.629641+08:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-05-30T19:32:27.7411165+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.27.9.138:51276->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:32:29.5901919+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:32:50.7943979+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:32:53.1382498+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:33:16.461004+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:33:18.7324232+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:33:46.8099693+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:33:48.7236533+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:34:24.0696576+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:34:27.7254746+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:35:20.8211898+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:35:28.3654064+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:36:41.8666551+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:36:49.4468832+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:38:03.2049511+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:38:10.5083776+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:39:24.2897188+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:39:31.5642208+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:40:45.3388676+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:40:52.6138716+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:42:06.7264172+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:42:08.4737044+08:00","level":"WARN","msg":"sender: taking a long time","seconds":600.0005288,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"w2r3nu17ecdy\" connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:42:13.7151193+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:43:27.7877187+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:43:34.7762422+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:44:02.6368832+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0004589,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:44:02.6399114+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0007929,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:44:04.1485139+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0007068,"work":"WorkRecord(*service_go_proto.Request_Keepalive); Control(local:true connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:44:12.6324306+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0003745,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:44:12.6324306+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0003745,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:44:12.6324306+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0003745,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:44:49.4913209+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:44:55.8556092+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:46:10.5305494+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:46:16.9069323+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:47:31.7664322+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:47:37.9976146+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:48:52.9822858+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:48:59.0568433+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:50:14.0492559+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:50:20.1692551+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:51:36.048336+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:51:41.2336394+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:52:08.475315+08:00","level":"WARN","msg":"sender: taking a long time","seconds":1200.0021394,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"w2r3nu17ecdy\" connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:52:57.6635824+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:53:02.410296+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:54:02.6405544+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0041301,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:54:02.6405544+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0014359,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:54:04.1491837+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0013766,"work":"WorkRecord(*service_go_proto.Request_Keepalive); Control(local:true connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:54:12.6330743+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0010182,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:54:12.6330743+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0010182,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:54:12.6330743+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":1200.0010182,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:54:18.7242426+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:54:23.4806314+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:55:39.7924581+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:55:39.7924581+08:00","level":"ERROR","msg":"sender: sendStopStatus: failed to get run stopped status: api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:55:39.7934779+08:00","level":"INFO","msg":"sender: succeeded after taking longer than expected","seconds":1411.3203023,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"w2r3nu17ecdy\" connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1297.1576124,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1297.1549182,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1287.1619806,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1287.1619806,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1295.6462296,"work":"WorkRecord(*service_go_proto.Request_Keepalive); Control(local:true connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T19:55:39.7940367+08:00","level":"INFO","msg":"runwork: succeeded after taking longer than expected","seconds":1287.1619806,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T19:55:44.554861+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:56:13.4724996+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:56:36.6501977+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:57:01.7541144+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:57:05.6225015+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:57:32.3998881+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:58:10.571677+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:58:26.6617317+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:59:04.60166+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T19:59:48.8094569+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:00:25.7331963+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:01:09.8886791+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:01:46.8709205+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:02:30.9560912+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:03:07.9080751+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:03:52.5090816+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:04:28.9997945+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:05:13.8856234+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:05:50.0736839+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:05:52.2634239+08:00","level":"WARN","msg":"sender: taking a long time","seconds":600.0004628,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"6zrp47xvhsni\" connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T20:06:34.9405325+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:07:11.2079291+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:07:42.6320543+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0003221,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T20:07:42.63766+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.000603,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T20:07:42.63766+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.000603,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T20:07:47.1649105+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.0008459,"work":"WorkRecord(*service_go_proto.Request_Keepalive); Control(local:true connection_id:\"127.0.0.1:51258\")"}
{"time":"2025-05-30T20:07:52.6326758+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.000532,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T20:07:52.6326758+08:00","level":"WARN","msg":"runwork: taking a long time","seconds":600.000532,"work":"WorkRecord(*service_go_proto.Record_Stats); Control(always_send:true)"}
{"time":"2025-05-30T20:07:56.1304832+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2717166816-sun-yat-sen-university/chatbot_project/5xkyptt8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T20:08:32.2641392+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
